name: Enmerkar
main: io.github.fechan.enmerkar.Enmerkar
version: 1.0
commands:
    editword:
      aliases: "addword"
      description: "Edit an existing word or add a word to your starting nation's dictionary."
      usage: "/editword <word> <english definition>"
      permission: io.github.fechan.enmerkar.canAddWords
    deleteword:
      description: "Delete a word from your starting nation's dictionary."
      usage: "/deleteword <word>"
      permission: io.github.fechan.enmerkar.canDeletewords
    define:
      aliases: [getword, odej]
      description: "Get the definition of a word from a your starting nation's dictionary."
      usage: "/define <word>"
      permission: io.github.fechan.enmerkar.canGetWords
    searchdefinitions:
      description: "Search through your original national dictionary's definitions for a key word or phrase."
      usage: "/searchdefinitions <key word or phrase>"
      permission: io.github.fechan.enmerkar.canGetWords
    setnation:
      description: "Set the original nationality of a player."
      usage: "/setnation <player> <nation>"
      permission: io.github.fechan.enmerkar.manageNationality   
    unsetnation:
      description: "Unset the original nationality of a player."
      usage: "/unsetnation <player>"
      permission: io.github.fechan.enmerkar.manageNationality
permissions:
  io.github.fechan.enmerkar.canAddWords:
    description: "Allows you to add words to your nation's dictionary."
    default: true
  io.github.fechan.enmerkar.canDeleteWords:
    description: "Allows you to delete words from your nation's dictionary."
    default: true
  io.github.fechan.enmerkar.canGetWords:
    description: "Allows you to read and search your nation's dictionary.."
    default: true
  io.github.fechan.enmerkar.manageNationality:
    default: true
    description: "Allows you to set and unset the nationality of any player."
    default: op
